permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: John Cheng
  email: 317019294@qq.cocm
  link: http://zqhxuyuan.github.io
  weibo: http://weibo.com/xuyuantree
  github: http://github.com/zqhxuyuan

# 站点信息
title: zqhxuyuan
description: My personal blog
url: http://zqhxuyuan.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: zqh

# 主题设置，自动激活某个标签
active: source

# 首页除了最新文章外显示分类
#cates: 
#  - BigData

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档